import React from 'react';

/**
 * CorpBaseDataForm Component
 * Shared form for CorpBase website information across ticket creation and editing
 *
 * @param {Object} props
 * @param {Function} props.register - react-hook-form register function
 * @param {Function} props.onGenerateDescription - callback for generating product description
 * @param {boolean} props.readOnly - whether form should be read-only
 * @param {boolean} props.showGenerateButton - whether to show generate description button
 */
const CorpBaseDataForm = ({
  register,
  onGenerateDescription,
  readOnly = false,
  showGenerateButton = true
}) => {
  return (
    <div className="card">
      <div className="card-header">
        <div className="flex items-center justify-between">
          <h3 className="text-lg font-medium text-gray-900">CorpBase Website Information</h3>
          {showGenerateButton && onGenerateDescription && !readOnly && (
            <button
              type="button"
              onClick={onGenerateDescription}
              className="inline-flex items-center px-3 py-1.5 border border-transparent text-xs font-medium rounded text-blue-700 bg-blue-100 hover:bg-blue-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500"
            >
              Generate Description
            </button>
          )}
        </div>
      </div>
      <div className="card-body space-y-6">
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-2">
            Product Description {showGenerateButton && !readOnly && '(Auto-generated by Claude)'}
          </label>
          <textarea
            {...register('corpbaseData.productDescription')}
            rows="4"
            className="form-input"
            placeholder={showGenerateButton && !readOnly ? "Click 'Generate Description' to auto-generate based on product name and chemical properties..." : "Product description"}
            readOnly={readOnly}
          />
        </div>

        <div className="grid grid-cols-1 gap-6 sm:grid-cols-2">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Website Title
            </label>
            <input
              {...register('corpbaseData.websiteTitle')}
              type="text"
              className="form-input"
              placeholder="SEO-optimized title for website"
              readOnly={readOnly}
            />
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Meta Description
            </label>
            <textarea
              {...register('corpbaseData.metaDescription')}
              rows="2"
              className="form-input"
              placeholder="Brief description for search engines (150-160 characters)"
              readOnly={readOnly}
            />
          </div>
        </div>

        <div>
          <label className="block text-sm font-medium text-gray-700 mb-2">
            Key Features & Benefits
          </label>
          <textarea
            {...register('corpbaseData.keyFeatures')}
            rows="3"
            className="form-input"
            placeholder="• High purity and quality&#10;• Suitable for research applications&#10;• Available in multiple sizes"
            readOnly={readOnly}
          />
        </div>

        <div className="grid grid-cols-1 gap-6 sm:grid-cols-2">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Applications
            </label>
            <textarea
              {...register('corpbaseData.applications')}
              rows="3"
              className="form-input"
              placeholder="List key applications..."
              readOnly={readOnly}
            />
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Target Industries
            </label>
            <textarea
              {...register('corpbaseData.targetIndustries')}
              rows="3"
              className="form-input"
              placeholder="Pharmaceutical, Biotechnology, Research..."
              readOnly={readOnly}
            />
          </div>
        </div>
      </div>
    </div>
  );
};

export default CorpBaseDataForm;
